debug: false
darktable-cli: /usr/bin/darktable-cli
assets-path: /var/photoprism
thumbnails-path: /var/photoprism/thumbnails
originals-path: /var/photoprism/photos/originals
import-path: /var/photoprism/photos/import
export-path: /var/photoprism/photos/export
server-ip:
server-mode: release
server-port: 80
database-driver: mysql
database-dsn: photoprism:photoprism@tcp(database:3306)/photoprism?parseTime=true