version: '3.3'

services:
  photoprism:
    build: .
    image: photoprism/photoprism
    command: tail -f /dev/null
    environment:
      - CODECOV_TOKEN

  database:
    image: mysql:latest
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-connections=1024
    environment:
      MYSQL_ROOT_PASSWORD: photoprism
      MYSQL_USER: photoprism
      MYSQL_PASSWORD: photoprism
      MYSQL_DATABASE: photoprism