version: '3.5'

## Latest Stable Release for QA
services:
  ## App Server
  ## Docs: https://docs.photoprism.org/
  photoprism-latest:
    image: photoprism/photoprism:latest
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    ports:
      - "2344:2342" # HTTP port (host:container)
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.photoprism-latest.loadbalancer.server.port=2342"
      - "traefik.http.routers.photoprism-latest.entrypoints=websecure"
      - "traefik.http.routers.photoprism-latest.rule=Host(`photoprism-latest.traefik.net`)"
      - "traefik.http.routers.photoprism-latest.tls.domains[0].main=traefik.net"
      - "traefik.http.routers.photoprism-latest.tls.domains[0].sans=*.traefik.net"
      - "traefik.http.routers.photoprism-latest.tls=true"
    environment:
      PHOTOPRISM_UID: ${UID:-1000}                   # User ID
      PHOTOPRISM_GID: ${GID:-1000}                   # Group ID
      PHOTOPRISM_ADMIN_PASSWORD: "photoprism"        # Admin password (min 4 characters)
      ## Public server URL incl http:// or https:// and /path, :port is optional
      PHOTOPRISM_SITE_URL: "https://photoprism-latest.traefik.net/"
      PHOTOPRISM_SITE_TITLE: "PhotoPrism"
      PHOTOPRISM_SITE_CAPTION: "Browse Your Life"
      PHOTOPRISM_SITE_DESCRIPTION: "Open-Source Photo Management"
      PHOTOPRISM_SITE_AUTHOR: "@photoprism_app"
      PHOTOPRISM_DEBUG: "true"
      PHOTOPRISM_READONLY: "false"
      PHOTOPRISM_PUBLIC: "true"
      PHOTOPRISM_EXPERIMENTAL: "false"
      PHOTOPRISM_SERVER_MODE: "debug"
      PHOTOPRISM_HTTP_HOST: "0.0.0.0"
      PHOTOPRISM_HTTP_PORT: 2342
      PHOTOPRISM_HTTP_COMPRESSION: "gzip"     # Improves transfer speed and bandwidth utilization (none or gzip)
      PHOTOPRISM_DATABASE_DRIVER: "mysql"
      PHOTOPRISM_DATABASE_SERVER: "mariadb:4001"
      PHOTOPRISM_DATABASE_NAME: "latest"
      PHOTOPRISM_DATABASE_USER: "root"
      PHOTOPRISM_DATABASE_PASSWORD: "photoprism"
      PHOTOPRISM_DISABLE_CHOWN: "false"       # Disables storage permission updates on startup
      PHOTOPRISM_DISABLE_BACKUPS: "false"     # Don't backup photo and album metadata to YAML files
      PHOTOPRISM_DISABLE_WEBDAV: "false"      # Disables built-in WebDAV server
      PHOTOPRISM_DISABLE_SETTINGS: "false"    # Disables Settings in Web UI
      PHOTOPRISM_DISABLE_PLACES: "false"      # Disables reverse geocoding and maps
      PHOTOPRISM_DISABLE_EXIFTOOL: "false"    # Don't create ExifTool JSON files for improved metadata extraction
      PHOTOPRISM_DISABLE_TENSORFLOW: "false"  # Don't use TensorFlow for image classification
      PHOTOPRISM_DETECT_NSFW: "false"         # Flag photos as private that MAY be offensive (requires TensorFlow)
      PHOTOPRISM_UPLOAD_NSFW: "false"         # Allows uploads that may be offensive
      PHOTOPRISM_DARKTABLE_PRESETS: "false"   # Enables Darktable presets and disables concurrent RAW conversion
      PHOTOPRISM_THUMB_FILTER: "lanczos"      # Resample filter, best to worst: blackman, lanczos, cubic, linear
      PHOTOPRISM_THUMB_UNCACHED: "true"       # Enables on-demand thumbnail rendering (high memory and cpu usage)
      PHOTOPRISM_THUMB_SIZE: 2048             # Pre-rendered thumbnail size limit (default 2048, min 720, max 7680)
      # PHOTOPRISM_THUMB_SIZE: 4096           # Retina 4K, DCI 4K (requires more storage); 7680 for 8K Ultra HD
      PHOTOPRISM_THUMB_SIZE_UNCACHED: 7680    # On-demand rendering size limit (default 7680, min 720, max 7680)
      PHOTOPRISM_JPEG_SIZE: 7680              # Size limit for converted image files in pixels (720-30000)
      PHOTOPRISM_JPEG_QUALITY: 92             # Set to 95 for high-quality thumbnails (25-100)
      TF_CPP_MIN_LOG_LEVEL: 0                 # Show TensorFlow log messages for development
    working_dir: "/photoprism"
    volumes:
      - "./storage/latest:/photoprism/storage"
      - "./storage/originals:/photoprism/originals"

## Join shared "photoprism-develop" network
networks:
  default:
    external:
      name: photoprism-develop
