version: '3.5'

services:
  # Uncomment to test with Caddy as proxy:
  #
  # caddy:
  #  image: abiosoft/caddy:1.0.3-no-stats
  #  depends_on:
  #    - photoprism
  #  ports:
  #    - 80:80
  #    - 443:443
  #    - 2015:2015
  #  volumes:
  #    - ./docker/development/Caddyfile:/etc/Caddyfile
  #  environment:
  #    ACME_AGREE: "true"

  photoprism:
    build: .
    image: photoprism/photoprism:develop
    depends_on:
      - photoprism-db
    ports:
      - "2342:2342" # Web Server (PhotoPrism)
      - "2343:2343"
    expose:
      - "2343" # Acceptance Tests
    volumes:
      - ".:/go/src/github.com/photoprism/photoprism"
      - "go-mod:/go/pkg/mod"
    shm_size: "2gb"
    environment:
      TF_CPP_MIN_LOG_LEVEL: 0 # Show TensorFlow log messages for development
      PHOTOPRISM_SITE_URL: "http://localhost:2342/"
      PHOTOPRISM_SITE_TITLE: "PhotoPrism"
      PHOTOPRISM_SITE_CAPTION: "Browse Your Life"
      PHOTOPRISM_SITE_DESCRIPTION: "Open-Source Personal Photo Management"
      PHOTOPRISM_SITE_AUTHOR: "@browseyourlife"
      PHOTOPRISM_DEBUG: "true"
      PHOTOPRISM_READONLY: "false"
      PHOTOPRISM_PUBLIC: "true"
      PHOTOPRISM_EXPERIMENTAL: "true"
      PHOTOPRISM_UPLOAD_NSFW: "false"
      PHOTOPRISM_DETECT_NSFW: "false"
      PHOTOPRISM_SERVER_MODE: "debug"
      PHOTOPRISM_HTTP_HOST: "0.0.0.0"
      PHOTOPRISM_HTTP_PORT: 2342
      PHOTOPRISM_DATABASE_DRIVER: "mysql"
      PHOTOPRISM_DATABASE_DSN: "root:photoprism@tcp(photoprism-db:4001)/photoprism?charset=utf8mb4,utf8&parseTime=true"
      PHOTOPRISM_TEST_DRIVER: "sqlite"
      PHOTOPRISM_TEST_DSN: ".test.db"
      PHOTOPRISM_ASSETS_PATH: "/go/src/github.com/photoprism/photoprism/assets"
      PHOTOPRISM_STORAGE_PATH: "/go/src/github.com/photoprism/photoprism/storage"
      PHOTOPRISM_ORIGINALS_PATH: "/go/src/github.com/photoprism/photoprism/storage/originals"
      PHOTOPRISM_IMPORT_PATH: "/go/src/github.com/photoprism/photoprism/storage/import"
      PHOTOPRISM_THUMB_FILTER: "lanczos" # Resample filter, best to worst: blackman, lanczos, cubic, linear
      PHOTOPRISM_THUMB_UNCACHED: "true" # On-demand rendering of default thumbnails (high memory and cpu usage)
      PHOTOPRISM_THUMB_SIZE: 2048 # Default thumbnail size limit (default 2048, min 720, max 3840)
      PHOTOPRISM_THUMB_LIMIT: 3840 # On-demand thumbnail size limit (default 2048, min 720, max 3840)
      PHOTOPRISM_JPEG_QUALITY: 90 # Use 95 for high-quality thumbnails (requires more storage)
      PHOTOPRISM_SIDECAR_JSON: "true" # Read metadata from JSON sidecar files created by exiftool
      PHOTOPRISM_SIDECAR_YAML: "true" # Backup photo metadata to YAML sidecar files

  photoprism-db:
    image: mariadb:10.5
    command: mysqld --port=4001 --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-connections=1024 --innodb-rollback-on-timeout=OFF --innodb-lock-wait-timeout=50
    expose:
      - "4001"
    ports:
      - "4001:4001" # MySQL (for tests)
    volumes:
      - "./scripts/reset-test-db.sql:/docker-entrypoint-initdb.d/reset-test-db.sql"
    environment:
      MYSQL_ROOT_PASSWORD: photoprism
      MYSQL_USER: photoprism
      MYSQL_PASSWORD: photoprism
      MYSQL_DATABASE: photoprism

  webdav-dummy:
    image: photoprism/webdav:20200327

volumes:
  go-mod:
    driver: local
